# Cloudflare Pages configuration for IPv6Poetry.org

name = "ipv6poetry"
compatibility_date = "2025-03-26"

# Deploy to IPv6Poetry.org in production
[env.production]
  route = "ipv6poetry.org/*"
  zone_id = ""  # You'll need to add your Cloudflare Zone ID here

# Build settings
[build]
  command = "bun install && bun run build"
  output_dir = "dist"
  base_dir = ""
  root_dir = "web"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'"

# Cache settings
[[headers]]
  for = "/wordlists/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"