name: Test and Deploy IPv6Poetry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-js:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: poetry-tools/js

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: poetry-tools/js/package-lock.json
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Test
      run: npm test
    
    - name: Build
      run: npm run build

  test-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: poetry-tools/python

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Lint
      run: |
        flake8 ipv6poetry
    
    - name: Test
      run: |
        pytest tests --cov=ipv6poetry

  compatibility-test:
    runs-on: ubuntu-latest
    needs: [test-js, test-python]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python Dependencies
      run: |
        cd poetry-tools/python
        pip install -e .
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install JS Dependencies
      run: |
        cd poetry-tools/js
        bun install
    
    - name: Run Compatibility Test
      run: ./tests/compatibility_test.js

  deploy-web:
    runs-on: ubuntu-latest
    needs: [compatibility-test]
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: web

    steps:
    - uses: actions/checkout@v3
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    - name: Install Dependencies
      run: bun install
    
    - name: Build
      run: bun run build
    
    - name: Publish to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages publish dist --project-name=ipv6poetry
        workingDirectory: web